=begin
Conovel API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class AuthController < ApplicationController

  def log_out
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def refresh_token
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
