=begin
Conovel API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class UsersController < ApplicationController

  def delete_user_by_me
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_novels_by_user_id
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def show
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_user_by_me
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def get_viewed_novels_by_me
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def update_user_by_me
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
