PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

  RSpec:
    enabled: true
    command: ['docker-compose', 'run', 'backend', 'bundle', 'exec', 'rspec']
    required_executable: 'rspec'
    description: 'Running RSpec tests'
    include: '**/*'
    exclude:
      - 'db/schema.rb'
      - 'db/migrate/*'

PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure

  IndexTags:
    enabled: true # Generate a tags file with `ctags` each time HEAD changes