# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # AuthController
  class AuthController < ApplicationController
    include ActionController::RequestForgeryProtection
    include ImageHelper

    # ApplicationControllerのauthenticate_requestをスキップ
    skip_before_action :authenticate_request, only: %i[create auth_failure refresh_token]

    # フロントエンドのURLを定数として定義
    FRONTEND_URL = ENV.fetch('REACT_APP_API_URL', 'http://localhost:3000')
    Rails.logger.debug("[DEBUG] Frontend URL: #{FRONTEND_URL}")

    # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    def create
      Rails.logger.debug("[DEBUG] Request params: #{params.to_json}")
      Rails.logger.debug("[DEBUG] Request env['omniauth.auth']: #{request.env['omniauth.auth'].to_json}")

      begin
        # OmniAuth から認証情報を取得
        user_data = request.env['omniauth.auth']
        if user_data.nil?
          handle_error_and_redirect('[ERROR] omniauth.auth が存在しません')
          return
        end
        Rails.logger.debug("[DEBUG] user_data: #{user_data.to_json}")

        # ユーザー情報を取得
        provider = user_data['provider']
        google_sub = user_data['uid']
        user_info = user_data['info']
        Rails.logger.debug("[DEBUG] provider: #{provider}")
        Rails.logger.debug("[DEBUG] google_sub: #{google_sub}")
        Rails.logger.debug("[DEBUG] user_info: #{user_info.to_json}")

        # ユーザー認証情報を確認
        user = User.find_by(google_sub:)
        if user.nil?
          Rails.logger.info('新規ユーザーが見つかりません。')

          # ユーザー情報を取得
          email = user_info['email']
          account_name = email.split('@').first # Googleのアカウント名
          birth_ym = Date.today.strftime('%Y%m') # ユーザー登録年月
          profile_icon_image_url = user_info['image'] # Googleのアイコン画像URL
          profile_icon_image = fetch_image_as_base64(profile_icon_image_url) # アイコン画像をBASE64に変換

          # 新しいユーザーを作成
          user = User.new(
            pen_name: account_name, # 仮のペンネーム
            nick_name: account_name, # 仮のニックネーム
            birth_ym:, # 仮の誕生年月
            agreed_terms_version: 0, # 未同意状態
            is_anonymous: true, # 匿名ユーザー（初期状態）
            profile_icon_image:, # 仮のアイコン画像URL
            email:,
            google_sub:
          )
          Rails.logger.debug("[DEBUG] 新しいユーザー情報 - user: #{user.to_json}")

          # 保存処理
          begin
            user.save!
            Rails.logger.info('[INFO] 新しいユーザーが作成されました')
            Rails.logger.debug("[DEBUG] ユーザー情報 - user: #{user.to_json}")
          rescue ActiveRecord::RecordInvalid => e
            handle_error_and_redirect("[ERROR] ユーザーの保存に失敗しました: #{e.record.errors.full_messages.join(', ')}")
            return
          end
        else
          Rails.logger.info('[INFO] 既存のユーザーが見つかりました。')
          Rails.logger.debug("[DEBUG] ユーザー情報 - user: #{user.to_json}")
        end

        # JWTトークン
        generate_jwt_token(user)

        # リフレッシュトークン
        generate_refresh_token(user)

        # アカウント画面にリダイレクト
        redirect_to "#{FRONTEND_URL}/account", allow_other_host: true
      rescue ActiveRecord::RecordInvalid => e
        # 保存に失敗した場合の処理
        handle_error_and_redirect("[ERROR] ユーザー作成に失敗しました: #{e.record.errors.full_messages.join(', ')}")
      rescue StandardError => e
        # その他のエラー処理
        handle_error_and_redirect("[ERROR] サーバーエラーが発生しました: #{e.message}")
      end
    end
    # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

    # リフレッシュトークンを使用して新しいJWTトークンを発行
    # rubocop:disable Metrics/AbcSize
    def refresh_token
      refresh_token = cookies.encrypted[:refresh_token]
      Rails.logger.debug("[DEBUG] refresh_token: #{refresh_token.to_json}")
      if refresh_token.present?
        user = User.find_by(refresh_token:)
        if user
          Rails.logger.info('[INFO] リフレッシュトークンでユーザーを特定しました')
          Rails.logger.debug("[DEBUG] ユーザー情報 - user: #{user.to_json}")

          # 新しいJWTトークンを発行
          generate_jwt_token(user)

          render json: { message: 'トークンが再発行されました' }, status: :ok
        else
          # リフレッシュトークンが無効な場合、削除する
          delete_tokens_from_cookies
          Rails.logger.error('[ERROR] リフレッシュトークンが無効です')
          render_error_response(401, 'リフレッシュトークンが無効です')
        end
      else
        # リフレッシュトークンが存在しない場合、念のためクッキーをクリア
        delete_tokens_from_cookies
        render_error_response(401, 'リフレッシュトークンが見つかりません')
      end
    end
    # rubocop:enable Metrics/AbcSize

    # OmniAuthのエラー処理
    def auth_failure
      delete_tokens_from_cookies

      error_message = request.env['omniauth.error.type'] || 'Unknown error'
      Rails.logger.error("[ERROR] 認証エラー - #{error_message}")

      # アカウント画面にリダイレクト
      handle_error_and_redirect("[ERROR] 認証エラーが発生しました。再度お試しください。: #{error_message}")
    end

    # TODO: ログアウト機能を実装する
    # def log_out
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    private

    # JWTトークンを生成してクッキーに保存する
    def generate_jwt_token(user)
      payload = { user_id: user.user_id }
      token = JwtService.encode(payload)
      Rails.logger.debug("[DEBUG] payload : #{payload.to_json}")
      cookies[:jwt_token] = {
        value: token,
        httponly: true, # JavaScriptからアクセスできないようにする
        secure: Rails.env.production?, # HTTPSのみで送信
        expires: 1.hour.from_now, # 有効期限
        same_site: :strict
      }
      Rails.logger.debug("[DEBUG] クッキーに保存されたJWTトークン: #{cookies[:jwt_token]}")
    end

    # リフレッシュトークンを生成してクッキーに保存する
    # rubocop:disable Metrics/AbcSize
    def generate_refresh_token(user)
      user.generate_refresh_token
      Rails.logger.debug("[DEBUG] 新しいリフレッシュトークン: #{user.refresh_token}")

      cookies.encrypted[:refresh_token] = {
        value: user.refresh_token,
        httponly: true,
        secure: Rails.env.production?,
        expires: 30.days.from_now, # 有効期限
        same_site: :strict
        # path: '/auth/refresh' # ここを有効にするとブラウザのcookieに保存されない
      }
      Rails.logger.debug("[DEBUG] クッキーに保存されたリフレッシュトークン: #{cookies.encrypted[:refresh_token]}")
    end
    # rubocop:enable Metrics/AbcSize

    # トークンをクッキーから削除する共通メソッド
    # rubocop:disable Metrics/AbcSize
    def delete_tokens_from_cookies
      # JWTトークンを保存しているクッキーを削除
      cookies.delete(:jwt_token)
      Rails.logger.info('[INFO] JWTトークンがクッキーから削除されました')
      Rails.logger.debug("[DEBUG] cookies[:jwt_token].to_json: #{cookies[:jwt_token].to_json}")

      # リフレッシュトークンを保存しているクッキーを削除
      cookies.delete(:refresh_token)
      Rails.logger.info('[INFO] リフレッシュトークンがクッキーから削除されました')
      Rails.logger.debug("[DEBUG] cookies[:refresh_token].to_json: #{cookies[:refresh_token].to_json}")
    end
    # rubocop:enable Metrics/AbcSize

    # エラーメッセージをフロントエンドにリダイレクト
    def handle_error_and_redirect(message)
      Rails.logger.error(message)
      redirect_to "#{FRONTEND_URL}/login", allow_other_host: true
    end
  end
end
