# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # EvaluationsController
  class EvaluationsController < ApplicationController
    # POST /v1/evaluations
    # rubocop:disable Metrics/AbcSize
    def create
      evaluation = Evaluation.find_or_initialize_by(sentence_id: evaluation_params[:sentence_id],
                                                    evaluator_user_id: current_user.user_id)
      evaluation.evaluation = evaluation_params[:evaluation]
      evaluation.save!

      evaluation_counts = Evaluation.where(sentence_id: evaluation.sentence_id).group(:evaluation).count
      evaluation_counts.default = 0

      render json: build_response(evaluation_params, evaluation_counts), status: :created
    end
    # rubocop:enable Metrics/AbcSize

    private

    # 評価のパラメータを取得
    def evaluation_params
      params.permit(:sentence_id, :evaluation)
    end

    # レスポンスを構築
    def build_response(evaluation_params, evaluation_counts)
      {
        sentence_id: evaluation_params[:sentence_id],
        evaluation_good_count: evaluation_counts['good'],
        evaluation_stay_count: evaluation_counts['stay']
      }
    end

    # カスタムエラーメッセージを定義
    def custom_record_invalid_message(exception)
      "投稿の評価に失敗しました。: #{exception.record.errors.full_messages.join(', ')}"
    end
  end
end
