# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # EvaluationsController
  class EvaluationsController < ApplicationController
    # POST /v1/evaluations
    # rubocop:disable Metrics/AbcSize
    def create
      # パラメータの存在チェック
      required_keys = %w[sentenceId evaluation]
      missing_keys = required_keys.reject { |key| params.key?(key) }
      if missing_keys.any?
        render_error_response(422, "必須項目が不足しています: #{missing_keys.join(', ')}")
        Rails.logger.error("[ERROR] 必須項目が不足しています: #{missing_keys.join(', ')}")
        return
      end

      evaluation = Evaluation.find_or_initialize_by(sentence_id: evaluation_params[:sentenceId],
                                                    evaluator_user_id: current_user_id)
      evaluation.evaluation = evaluation_params[:evaluation]
      evaluation.save!

      evaluation_counts = Evaluation.where(sentence_id: evaluation.sentence_id).group(:evaluation).count
      evaluation_counts.default = 0

      render json: build_response(evaluation_params, evaluation_counts), status: :created
    end
    # rubocop:enable Metrics/AbcSize

    private

    # 評価のパラメータを取得
    def evaluation_params
      params.permit(:sentenceId, :evaluation)
    end

    # レスポンスを構築
    def build_response(evaluation_params, evaluation_counts)
      {
        sentenceId: evaluation_params[:sentenceId],
        evaluationGoodCount: evaluation_counts['good'],
        evaluationStayCount: evaluation_counts['stay']
      }
    end

    # カスタムエラーメッセージを定義
    def custom_record_invalid_message(exception)
      "投稿の評価に失敗しました。: #{exception.record.errors.full_messages.join(', ')}"
    end
  end
end
