# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # NovelsController
  class NovelsController < ApplicationController
    # def show # 別チケットで実装予定
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # GET /v1/novels
    def index
      novels = Title.eager_load(:author_user, title_genres: :genre, sentences: :evaluations).all

      render json: novels.map { |novel| build_novel_data(novel) }
    end

    private

    # rubocop:disable Metrics/AbcSize
    def build_novel_data(novel)
      author_user = novel.author_user
      title_genres = novel.title_genres.map(&:genre)
      sentences = novel.sentences
      total_good_count = evaluation_good_count(novel)

      {
        title_id: novel.title_id,
        title: novel.title,
        famous_sentence_text: famous_sentence(novel)&.sentence,
        author_user_id: author_user.user_id,
        author_user_name: author_user.pen_name,
        profile_icon_image: author_user.profile_icon_image,
        title_genres: title_genres.map(&:genre_name),
        is_new: sentences.max_by(&:created_at).created_at > NEW_PERIOD_DAYS.days.ago,
        is_famous: total_good_count >= FAMOUS_EVALUATION_THRESHOLD,
        view_count: sentences.sum(&:viewed_sentences_count),
        evaluation_good_count: total_good_count,
        created_at: novel.created_at,
        updated_at: novel.updated_at
      }
    end
    # rubocop:enable Metrics/AbcSize

    def famous_sentence(novel)
      novel.sentences
           .joins(:evaluations)
           .where(evaluations: { evaluation: 'good' })
           .group('sentences.sentence_id')
           .order(Arel.sql('COUNT(evaluations.sentence_id) DESC'))
           .first
    end

    def evaluation_good_count(novel)
      novel.sentences
           .joins(:evaluations)
           .where(evaluations: { evaluation: 'good' })
           .count
    end

    # カスタムエラーメッセージを定義
    def custom_record_invalid_message(exception)
      "小説リストの取得に失敗しました。: #{exception.record.errors.full_messages.join(', ')}"
    end
  end
end
