# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # NovelsController
  class NovelsController < ApplicationController
    # GET /v1/novels
    def index
      novels = Title.includes(:author_user, title_genres: :genre).all

      render json: novels.map { |novel| build_novel_data(novel) }
    rescue StandardError
      render_error_response(422, '小説リストの取得に失敗しました。')
    end

    # GET /v1/novels/{title_id}
    def show
      novel = Title.includes(:author_user, title_genres: :genre).find(params[:title_id])

      render json: build_novel_detail_data(novel)
    rescue StandardError
      render_error_response(422, '小説の概要の取得に失敗しました。')
    end

    private

    # rubocop:disable Metrics/AbcSize
    def build_novel_data(novel)
      author_user = novel.author_user
      total_good_count = evaluation_good_count(novel)

      {
        title_id: novel.title_id,
        title: novel.title,
        famous_sentence_text: famous_sentence_text(novel),
        author_user_id: author_user.user_id,
        author_user_name: author_user.pen_name,
        profile_icon_image: author_user.profile_icon_image,
        title_genres: novel.title_genres.map { |title_genre| title_genre.genre.genre_name },
        is_new: novel.sentences.order(created_at: :desc).first.created_at > NEW_PERIOD_DAYS.days.ago,
        is_famous: total_good_count >= FAMOUS_EVALUATION_THRESHOLD,
        view_count: view_count(novel),
        evaluation_good_count: total_good_count,
        created_at: novel.created_at,
        updated_at: novel.updated_at
      }
    end
    # rubocop:enable Metrics/AbcSize

    def build_novel_detail_data(novel)
      data = build_novel_data(novel)
      data.merge(
        main_copy: novel.main_copy,
        sentence_user_count: novel.sentences.count,
        sentence_hierarchy_count: novel.sentences.maximum(:sentence_hierarchy),
        reader_count: novel.sentences.joins(:viewed_sentences).distinct.count(:viewed_user_id),
        overview: novel.overview
      )
    end

    def famous_sentence_text(novel)
      famous_sentence(novel)&.sentence
    end

    def famous_sentence(novel)
      novel.sentences
           .joins(:evaluations)
           .group('sentences.sentence_id')
           .order(Arel.sql('COUNT(evaluations.sentence_id) DESC'))
           .first
    end

    def view_count(novel)
      novel.sentences.sum(:viewed_sentences_count)
    end

    def evaluation_good_count(novel)
      novel.sentences.joins(:evaluations).where(evaluations: { evaluation: 'good' }).count
    end
  end
end
