# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # SentencesController
  class SentencesController < ApplicationController
    def show
      result = FindSentenceService.new(params[:sentence_id]).call
      if result[:success]
        render_success_response(result[:sentence])
      else
        render_error_response(result[:error])
      end
    end

    def render_success_response(sentence)
      response_data = build_response_data(sentence)
      render json: build_response(response_data), status: :ok
    end

    private

    def build_response_data(sentence)
      {
        sentence:,
        user: find_user(sentence.sentence_user_id),
        evaluation_counts: fetch_evaluation_counts(sentence.id),
        parent_sentence: find_parent_sentence(sentence.parent_sentence_id),
        parent_parallel_sentences: find_parent_parallel_sentences(sentence),
        children_sentences: find_children_sentences(sentence.id)
      }
    end

    def find_user(user_id)
      User.find(user_id)
    end

    def fetch_evaluation_counts(sentence_id)
      {
        good: Evaluation.where(sentence_id:, evaluation: 'good').count,
        stay: Evaluation.where(sentence_id:, evaluation: 'stay').count
      }
    end

    def find_parent_sentence(parent_sentence_id)
      return nil if parent_sentence_id.nil?

      Sentence.find_by(sentence_id: parent_sentence_id)
    end

    def find_parent_parallel_sentences(sentence)
      parent_sentence = find_parent_sentence(sentence.parent_sentence_id)
      return [] if parent_sentence.nil?

      Sentence.where(parent_sentence_id: parent_sentence.parent_sentence_id).where.not(sentence_id: parent_sentence.id)
    end

    def find_children_sentences(parent_sentence_id)
      Sentence.where(parent_sentence_id:)
    end

    # rubocop:disable Metrics/MethodLength
    def build_sentence_response(sentence, user = nil, evaluation_counts = nil)
      return nil if sentence.nil?

      user ||= find_user(sentence.sentence_user_id)
      evaluation_counts ||= fetch_evaluation_counts(sentence.id)

      {
        sentence_id: sentence.id,
        sentence: sentence.sentence,
        sentence_user_id: sentence.sentence_user_id,
        sentence_user_name: user.pen_name,
        profile_icon_image: user.profile_icon_image,
        evaluation_good_count: evaluation_counts[:good],
        evaluation_stay_count: evaluation_counts[:stay],
        created_at: format_time(sentence.created_at),
        updated_at: format_time(sentence.updated_at)
      }
    end
    # rubocop:enable Metrics/MethodLength

    def build_parent_parallel_responses(sentences)
      sentences.map do |sentence|
        build_sentence_response(sentence)
      end
    end

    def build_children_responses(sentences)
      sentences.map do |sentence|
        build_sentence_response(sentence)
      end
    end

    def build_response(data)
      {
        main: build_sentence_response(data[:sentence], data[:user], data[:evaluation_counts]),
        parent: build_sentence_response(data[:parent_sentence]),
        parent_parallel: build_parent_parallel_responses(data[:parent_parallel_sentences]),
        children: build_children_responses(data[:children_sentences])
      }
    end

    def format_time(time)
      time.in_time_zone('Asia/Tokyo')
    end

    def render_error_response(error)
      render json: { error: }, status: :not_found
    end
  end
end
