# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # UsersController
  class UsersController < ApplicationController
    # ApplicationControllerのauthenticate_requestをスキップ
    # skip_before_action :authenticate_request, only: %i[current_user_id]

    # TODO: 以下のアクションを実装する

    # def delete_user_by_me
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    def current_user_id
      Rails.logger.debug("[DEBUG] カレントユーザー - @current_user_id: #{@current_user_id.to_json}")

      if @current_user_id.present?
        render json: { user_id: @current_user_id }, status: :ok
      else
        render_error_response(401, 'カレントユーザーのid取得に失敗しました')
      end
    end

    # def get_novels_by_user_id
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # def show
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # def get_user_by_me
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # def get_viewed_novels_by_me
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # def update_user_by_me
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end
  end
end
