# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # UsersController
  class UsersController < ApplicationController
    include ErrorResponseHelper
    # authenticate_requestをスキップ
    # skip_before_action :authenticate_request, only: %i[get_novels_by_user_id show]

    # ユーザーが投稿している小説リストを取得
    # def get_novels_by_user_id
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # IDで自分以外のユーザーアカウント情報を取得
    # def show
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # rubocop:disable Metrics/AbcSize
    # 自分自身のユーザーアカウント情報
    def get_user_by_me
      Rails.logger.debug("[DEBUG] カレントユーザー - @current_user_id: #{@current_user_id.to_json}")

      if @current_user_id.present?
        user = User.includes(sentences: :evaluations).find_by(user_id: @current_user_id)
        Rails.logger.debug("[DEBUG] ユーザー情報: #{user.to_json}") if user

        if user
          good_count = user.sentences.flat_map(&:evaluations).count { |e| e.evaluation == 'good' }
          Rails.logger.debug("[DEBUG] 評価数: #{good_count}")

          render json: {
            userId: user.user_id,
            penName: user.pen_name,
            nickName: user.nick_name,
            profileIconImage: user.profile_icon_image,
            evaluationGoodCount: good_count,
            createdAt: user.created_at,
            updatedAt: user.updated_at,
            birthYm: user.birth_ym,
            isAnonymous: user.is_anonymous,
            agreedTermsVersion: user.agreed_terms_version
          }, status: :ok
        else
          render_error_response(404, 'ユーザーが見つかりません')
        end
      else
        render_error_response(401, 'カレントユーザーのid取得に失敗しました')
      end
    end
    # rubocop:enable Metrics/AbcSize

    # 自分自身が閲覧している小説リストを取得
    # def get_viewed_novels_by_me
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end
  end
end
