# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

module V1
  # UsersController
  class UsersController < ApplicationController
    include ErrorResponseHelper
    # authenticate_requestをスキップ
    # skip_before_action :authenticate_request, only: %i[get_novels_by_user_id show]

    def delete_user_by_me
      Rails.logger.debug("[DEBUG] カレントユーザー - @current_user_id: #{@current_user_id.to_json}")

      user = User.find_by(user_id: @current_user_id)
      if user.nil?
        render_error_response(422, 'ユーザーが見つかりません。')
        return
      end

      begin
        user.destroy! # destroy! を使用して例外を発生させる
        # Rails.logger.info("[DEBUG] セッションの内容（リセット前）: #{session.to_hash.inspect}")

        # セッションをリセット
        # reset_session #不要？
        # Rails.logger.info('[INFO] セッションがリセットされました')
        # Rails.logger.info("[DEBUG] セッションの内容（リセット後）: #{session.to_hash.inspect}")

        # ステータスコード 200 を返す
        head :ok
      rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotDestroyed => e
        render_error_response(422, "ユーザーアカウント情報の削除に失敗しました。: #{e.message}")
      end
    end
    # ユーザーが投稿している小説リストを取得
    # def get_novels_by_user_id
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # IDで自分以外のユーザーアカウント情報を取得
    # def show
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # rubocop:disable Metrics/AbcSize
    # 自分自身のユーザーアカウント情報
    def get_user_by_me
      Rails.logger.debug("[DEBUG] カレントユーザー - @current_user_id: #{@current_user_id.to_json}")

      if @current_user_id.present?
        user = User.includes(sentences: :evaluations).find_by(user_id: @current_user_id)
        Rails.logger.debug("[DEBUG] ユーザー情報: #{user.to_json}") if user

        if user
          good_count = user.sentences.flat_map(&:evaluations).count { |e| e.evaluation == 'good' }
          Rails.logger.debug("[DEBUG] 評価数: #{good_count}")

          render json: {
            userId: user.user_id,
            penName: user.pen_name,
            nickName: user.nick_name,
            profileIconImage: user.profile_icon_image,
            evaluationGoodCount: good_count,
            createdAt: user.created_at,
            updatedAt: user.updated_at,
            birthYearAndMonth: user.birth_ym,
            isAnonymous: user.is_anonymous
          }, status: :ok
        else
          render_error_response(404, 'ユーザーが見つかりません')
        end
      else
        render_error_response(401, 'カレントユーザーのid取得に失敗しました')
      end
    end
    # rubocop:enable Metrics/AbcSize

    # 自分自身が閲覧している小説リストを取得
    # def get_viewed_novels_by_me
    #   # Your code here

    #   render json: {"message" => "yes, it worked"}
    # end

    # rubocop:disable Metrics/AbcSize
    def update_user_by_me
      # パラメータの存在チェック
      required_keys = %w[penName nickName isAnonymous birthYm agreedTermsVersion]
      return unless check_required_keys(params, required_keys)

      user = User.find_by!(user_id: @current_user_id)
      Rails.logger.debug("[DEBUG]カレントユーザー情報 - user: #{user.to_json}")

      # パラメータをスネークケースからキャメルケースに変換
      transformed_params = params.transform_keys(&:underscore)
      Rails.logger.debug("[DEBUG] 変換後のパラメータ: #{transformed_params.to_json}")

      if user.update!(transformed_params.permit(:pen_name, :nick_name, :is_anonymous, :profile_icon_image, :birth_ym,
                                                :agreed_terms_version, :remarks))
        user.reload # 最新状態取得
        evaluation_good_count = Evaluation.joins(:sentence)
                                          .where(sentences: { sentence_user_id: user.user_id })
                                          .where(evaluation: 'good')
                                          .count
        Rails.logger.debug("[DEBUG] Evaluation count query result: #{evaluation_good_count}")

        render json: {
          userId: user.user_id,
          penName: user.pen_name,
          nickName: user.nick_name,
          birthYm: user.birth_ym,
          isAnonymous: user.is_anonymous,
          profileIconImage: user.profile_icon_image,
          evaluationGoodCount: evaluation_good_count,
          createdAt: user.created_at,
          updatedAt: user.updated_at
        }, status: :ok
      end
    end
    # rubocop:enable Metrics/AbcSize

    private

    # カスタムエラーメッセージを定義
    def custom_record_invalid_message(exception)
      "ユーザーアカウント情報の更新に失敗しました。: #{exception.record.errors.full_messages.join(', ')}"
    end
  end
end
