=begin
Conovel API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "sentence".pluralize.to_sym, id: false do |t|
      t.integer :sentence_id
      t.string :sentence
      t.integer :sentence_user_id
      t.string :sentence_user_name
      t.string :profile_icon_image
      t.integer :evaluation_good_count
      t.integer :evaluation_stay_count
      t.datetime :created_at
      t.datetime :updated_at

      t.timestamps
    end

    create_table "view_sentence".pluralize.to_sym, id: false do |t|
      t.string :main
      t.string :parent
      t.string :parent_parallel
      t.string :children

      t.timestamps
    end

  end
end
