=begin
Sentences API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "_sentences__sentence_id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :main

      t.timestamps
    end

    create_table "_sentences__sentence_id__get_200_response_main".pluralize.to_sym, id: false do |t|
      t.integer :sentence_id
      t.string :sentence
      t.datetime :created_at
      t.datetime :updated_at

      t.timestamps
    end

  end
end
