=begin
Conovel API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "conflict_sentence".pluralize.to_sym, id: false do |t|
      t.string :error
      t.integer :sentence_id

      t.timestamps
    end

    create_table "error_response".pluralize.to_sym, id: false do |t|
      t.string :error

      t.timestamps
    end

    create_table "error_response_error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :message

      t.timestamps
    end

    create_table "evaluate_sentence".pluralize.to_sym, id: false do |t|
      t.integer :sentence_id
      t.string :evaluation

      t.timestamps
    end

    create_table "novel_detail".pluralize.to_sym, id: false do |t|
      t.integer :title_id
      t.string :title
      t.string :famous_sentence_text
      t.integer :author_user_id
      t.string :author_pen_name
      t.string :profile_icon_image
      t.string :title_genres
      t.boolean :is_new
      t.boolean :is_famous
      t.integer :view_count
      t.integer :evaluation_good_count
      t.datetime :created_at
      t.datetime :updated_at
      t.string :main_copy
      t.integer :sentence_user_count
      t.integer :sentence_hierarchy_count
      t.integer :reader_count
      t.string :overview
      t.integer :first_sentence_id

      t.timestamps
    end

    create_table "novel_list_item".pluralize.to_sym, id: false do |t|
      t.integer :title_id
      t.string :title
      t.string :famous_sentence_text
      t.integer :author_user_id
      t.string :author_pen_name
      t.string :profile_icon_image
      t.string :title_genres
      t.boolean :is_new
      t.boolean :is_famous
      t.integer :view_count
      t.integer :evaluation_good_count
      t.datetime :created_at
      t.datetime :updated_at

      t.timestamps
    end

    create_table "post_sentence".pluralize.to_sym, id: false do |t|
      t.integer :parent_sentence_id
      t.datetime :parent_updated_at
      t.string :sentence

      t.timestamps
    end

    create_table "sentence".pluralize.to_sym, id: false do |t|
      t.integer :sentence_id
      t.string :sentence
      t.integer :sentence_user_id
      t.string :sentence_pen_name
      t.string :profile_icon_image
      t.integer :evaluation_good_count
      t.integer :evaluation_stay_count
      t.string :user_evaluation
      t.datetime :created_at
      t.datetime :updated_at

      t.timestamps
    end

    create_table "sentence_id_only".pluralize.to_sym, id: false do |t|
      t.integer :sentence_id

      t.timestamps
    end

    create_table "update_user".pluralize.to_sym, id: false do |t|
      t.string :pen_name
      t.string :nick_name
      t.boolean :is_anonymous
      t.string :profile_icon_image
      t.string :birth_ym
      t.integer :agreed_terms_version
      t.string :remarks

      t.timestamps
    end

    create_table "user".pluralize.to_sym, id: false do |t|
      t.integer :user_id
      t.string :pen_name
      t.string :nick_name
      t.string :profile_icon_image
      t.integer :evaluation_good_count
      t.datetime :created_at
      t.datetime :updated_at

      t.timestamps
    end

    create_table "view_evaluation".pluralize.to_sym, id: false do |t|
      t.integer :sentence_id
      t.integer :evaluation_good_count
      t.integer :evaluation_stay_count
      t.string :user_evaluation

      t.timestamps
    end

    create_table "view_me_user".pluralize.to_sym, id: false do |t|
      t.integer :user_id
      t.string :pen_name
      t.string :nick_name
      t.string :profile_icon_image
      t.integer :evaluation_good_count
      t.datetime :created_at
      t.datetime :updated_at
      t.string :birth_ym
      t.boolean :is_anonymous
      t.integer :agreed_terms_version

      t.timestamps
    end

    create_table "view_sentence".pluralize.to_sym, id: false do |t|
      t.string :main
      t.string :parent
      t.string :parallels
      t.string :children

      t.timestamps
    end

  end
end
