# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

# sentences API
Rails.application.routes.draw do
  def add_openapi_route(http_method, path, opts = {})
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  # namespace
  namespace :v1 do
    add_openapi_route 'POST', '/auth/logout', controller_name: 'auth', action_name: 'log_out'
    add_openapi_route 'POST', '/auth/refresh', controller_name: 'auth', action_name: 'refresh_token'
    add_openapi_route 'POST', '/evaluations', controller_name: 'evaluations', action_name: 'create'
    add_openapi_route 'GET', '/novels/{titleId}', controller_name: 'novels', action_name: 'show'
    add_openapi_route 'GET', '/novels', controller_name: 'novels', action_name: 'index'
    add_openapi_route 'GET', '/sentences/{sentenceId}', controller_name: 'sentences', action_name: 'show'
    add_openapi_route 'POST', '/sentences', controller_name: 'sentences', action_name: 'create'
    add_openapi_route 'POST', '/users/me/delete', controller_name: 'users', action_name: 'delete_user_by_me'
    # add_openapi_route 'GET', '/users/{userId}/posted_novels', controller_name: 'users', action_name: 'get_novels_by_user_id'
    # add_openapi_route 'GET', '/users/{userId}', controller_name: 'users', action_name: 'show'
    add_openapi_route 'GET', '/users/me', controller_name: 'users', action_name: 'get_user_by_me'
    # add_openapi_route 'GET', '/users/me/viewedNovels', controller_name: 'users', action_name: 'get_viewed_novels_by_me'
    add_openapi_route 'POST', '/users/me/update', controller_name: 'users', action_name: 'update_user_by_me'
  end

  # google認証にアクセス
  get '/auth/:provider/callback', to: 'v1/auth#create'

  # Swagger UI
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
end
