=begin
Conovel API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class PostSentence < ApplicationRecord
  validates_presence_of :parent_sentence_id
  validates_presence_of :parent_updated_at
  validates_presence_of :sentence

end
