=begin
Conovel API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class UpdateUser < ApplicationRecord
  validates_presence_of :pen_name
  validates_presence_of :nick_name
  validates_presence_of :is_anonymous
  validates_presence_of :birth_ym
  validates_presence_of :agreed_terms_version

end
