=begin
Conovel API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class ViewSentence < ApplicationRecord

  serialize :parent_parallel, Array
  serialize :children, Array
end
