# frozen_string_literal: true

# Sentences API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

# SentencesController
class SentencesController < ApplicationController
  def v1_sentences_sentence_id_get
    # render json: { 'message' => 'yes, it worked' }
    sentence = Sentence.find(params[:sentence_id])
    render json: {
      main: {
        sentence_id: sentence.id,
        sentence: sentence.sentence,
        created_at: sentence.created_at,
        updated_at: sentence.updated_at
      }
    }, status: :ok
    # rescue ActiveRecord::RecordNotFound
    #   render json: { error: 'Sentence not found' }, status: :not_found
  end
end
