# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

# Sentence model handles the sentences in the application.
# It validates the presence of the sentence attribute.
class Sentence < ApplicationRecord
  # 論理削除
  acts_as_paranoid

  # アソシエーション
  belongs_to :user, foreign_key: 'sentence_user_id'
  belongs_to :title
  belongs_to :parent, class_name: 'Sentence', optional: true, foreign_key: 'parent_sentence_id'
  has_many :children, class_name: 'Sentence', foreign_key: 'parent_sentence_id'
  has_many :evaluations, foreign_key: 'sentence_id'

  # バリデーション
  validates :sentence, presence: true
  validates :sentence_user_id, presence: true
  validates :title_id, presence: true
  validates :sentence_hierarchy, presence: true

  # クラスメソッド
  def self.find_by_id(sentence_id)
    find(sentence_id)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end
