# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

# Sentence model handles the sentences in the application.
# It validates the presence of the sentence attribute.
class Sentence < ApplicationRecord
  validates :sentence, presence: true

  def self.find_by_id(sentence_id)
    find(sentence_id)
  rescue ActiveRecord::RecordNotFound
    nil
  end
end
