# frozen_string_literal: true

# Conovel API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

# 親のパラレル投稿と子投稿（複数件＝配列）
class ViewSentence < ApplicationRecord
  serialize :parent_parallel, Array
  serialize :children, Array
end
